### ISSUE TITLE
Read yaml with function

### ISSUE THREAD

**Issue by gabrielpeixoto** [wwilsman/js-yaml-loader#6] opened 2019-04-05 02:21 UTC
I am trying to read this yaml file:
```yaml
function: !!js/function >
  function foobar() {
    return 'Wow! JS-YAML Rocks!';
  }
```

My _webpack.config.js:
```javascript
    {
        test: /\.yaml$/,
        use: [{
            loader: 'js-yaml-loader',
            options: {
                safe: false
            }
        }]
    }
```
But i'm getting this error:
`Module build failed: Error: Final loader didn't return a Buffer or String`

**Comment by wwilsman** [comment] 2019-04-05 17:21
Hey @gabrielpeixoto, thanks for opening the issue. Could you provide a repo for the project where you're seeing this happen, or maybe just a minimum reproduction of the error?

I tried reproducing it myself by copying your yaml file and webpack config but it seemed to work for me without a problem.

<img width="1687" alt="Screen Shot 2019-04-05 at 12 18 13 PM" src="https://user-images.githubusercontent.com/5005153/55644978-006aec00-579d-11e9-81ab-fc19a59e490f.png">

**Comment by wwilsman** [comment] 2019-04-11 20:08
It's been a few days with no reply, so I'm going to close this since I wasn't able to reproduce.

**Closed as completed by wwilsman** 2019-04-11 20:08 UTC
