### ISSUE TITLE
How to read yaml file in React JS

### ISSUE THREAD

**Issue by examineyou65** [wwilsman/js-yaml-loader#16] opened 2019-11-30 06:31 UTC
I am  used following way to read yaml file in React js
import React from 'react';
import logo from './logo.svg';
import './App.css';
import data from "./data.yml";
const title = data;

function App() {
  return (
    <div className="App">
<p>this is yml{data.version}{title}</p>
    </div>
  );
}
But nothing return. Please can you give some suggestion for read yaml

**Comment by wwilsman** [comment] 2019-12-02 19:13
Hey there!

Have you added the loader to your webpack config as mentioned in the [usage section](https://github.com/wwilsman/js-yaml-loader#usage)? If you're having trouble with that, it might be worth checking out Webpack's official [loader docs](https://webpack.js.org/concepts/loaders/#using-loaders).

If you do have that set up, are you maybe defining multiple documents in your yaml file? When this loader detects multiple documents in a single yaml file, it will return an array for `data`. 

Have you tried `console.log(data)` to see what's there? If `data` is undefined, `data.version` would throw an error; so it seems that _something is returned_, just may not be what you're expecting. What does your yaml file look like?

**Comment by joepagan** [comment] 2020-02-06 08:04
Hey, experiencing the same thing, could you highlight what this issue is?

webpack conf:
```js
module: {
      rules: [
        {
          test: /\.yaml$/,
          use: 'js-yaml-loader',
        },
```

In my app:
```jsx
import doc from './tree.yml';
class Tree extends React.Component {
  componentDidMount() {
    console.log('componentDidMount');
    console.log(doc);
  }
```

output:
```
componentDidMount
/static/media/tree.b4c6e7bf.yml
```

**Comment by wwilsman** [comment] 2020-02-06 16:06
Hey @joepagan! Looks like your rule test is for `.yaml` but your file ends in `.yml` (no `a`).

I realize now that this is exactly what's in the readme, so I'll adjust that to reflect a better rule test.

**Comment by wwilsman** [comment] 2020-02-06 16:09
@examineyou65 Was this perhaps also the problem in your app? It seems like it might be if you copied the rule from the readme. Now that the readme is updated, I'm going to close this issue. Feel free to reopen if you think there's something else going on

**Closed as completed by wwilsman** 2020-02-06 16:09 UTC

**Comment by joepagan** [comment] 2020-02-06 22:04
Hey @wwilsman thanks for pointing that, I feel like I should hang my head in shame for not spotting that 😩 .
Anyway, that is a bit more successful, though I am unable to get any file contents.
This time in place of the path I get:

```js
console.log(doc);
```

outputs:

```js
module.exports = __webpack_public_path__ + "static/media/tree.b4c6e7bf.yml";
```
Sorry I'm not very familiar with the `yaml-loader` and not sure what usage looks like. Do you have any further suggestions?

I have tried setting safe false:
```js
        {
          test: /\.ya?ml$/,
          use: [{
            loader: 'js-yaml-loader',
            options:{
              safe: false,
            }
          }],
        },
```
however, this doesn't have any effect on the output and is the same as above.

**Comment by wwilsman** [comment] 2020-02-07 19:20
Hmmm. Very strange. I wonder if another loader is causing interference? And if so, I wonder if switching the loader order would help? 🤔 

If you could create a minimum, reproducable example. That would help a ton for debugging

**Comment by joepagan** [comment] 2020-02-07 20:33
Hey mate, I've set that up for you, it's doing the same thing here too:
https://github.com/joepagan/js-yaml-loader-test

**Comment by wwilsman** [comment] 2020-02-07 20:54
Thanks!

I see now that it's `file-loader` causing the issue. I should've guessed since you're seeing `__webpack_public_path__` in your log.

If you add the yaml regex to the exclude section of that loader, it works!

```
exclude: [/\.(js|mjs|jsx|ts|tsx)$/, /\.html$/, /\.json$/, /\.ya?ml$/]
```

**Comment by joepagan** [comment] 2020-02-07 21:13
That's it thanks for taking a look! My example repo was just built with the create-react-app so please reference this in the readme!
Thanks for your work on this.

**Comment by wwilsman** [comment] 2020-02-07 21:33
Good call. [Added to the readme](https://github.com/wwilsman/js-yaml-loader#with-create-react-app) 👍

**Comment by j-lee8** [comment] 2020-09-01 07:49
Is there any way to load a yml file with an app that hasn't been ejected? We have an OpenAPI spec as a yaml file and need to load it but it doesn't seem to even detect the file type (we did a test by changing it to be .json and it was detected). I'm guessing it's because there's no yaml loader. We can not eject the app so this isn't a possibility.

**Comment by wwilsman** [comment] 2020-09-01 18:13
Hey @JavaJamie! Unfortunately, I don't think that's possible. I don't personally use CRA, but I believe their philosophy is if you want to customize or change any configuration, you have to eject.

From their [README](https://github.com/facebook/create-react-app#whats-included):

> The tradeoff is that these tools are preconfigured to work in a specific way. If your project needs more customization, you can "eject" and customize it, but then you will need to maintain this configuration.

You're correct that the reason it doesn't detect the filetype is because there is no yaml loader included with CRA. You'll either be forced to eject to use a loader they don't include, or they'd need to add a yaml loader to CRA's webpack config.

**Comment by j-lee8** [comment] 2020-09-02 08:29
Hi @wwilsman! Thank you for your response. Ah, that was my concern. As useful as CRA is, it can also be a roadblock in times of need and this isn't the first time we've experienced it. We managed to solve this without ejecting by hosting the file then referencing it by the URL (We're using swagger-client and this is one of their recommended approaches). Just make sure headers are set appropriately for CORs (if it's in a different domain) and that it displays the yaml in the browser rather than downloading it.
